"""Add sets table and set_id to flashcards

Revision ID: bb5bfb619a61
Revises: 87c39c74aa2f
Create Date: 2025-06-22 17:42:01.962244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5bfb619a61'
down_revision: Union[str, Sequence[str], None] = '87c39c74aa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('english', sa.VARCHAR(length=80), nullable=False),
    sa.Column('russian', sa.VARCHAR(length=80), nullable=False),
    sa.Column('meaning', sa.VARCHAR(length=120), nullable=True),
    sa.Column('pos', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
